### ISSUE TITLE
关于代理配置的问题

### ISSUE THREAD

**Issue by kumiko-desu** [anlen123/nonebot_plugin_pixiv#1]
因为我的服务器是海外的不需要代理，可以直连pixiv，不配置代理反而无法使用了，所以 `proxy_aiohttp` 一定需要配置好像不太妥当，作者是否可以考虑调整一下，将其修改为可选配置呢，非常感谢。

**Comment by anlen123** [comment]
好的，谢谢你使用本插件，你的建议会在最近的更新中修改。
