### ISSUE TITLE
关于p站cookie设置

### ISSUE THREAD

**Issue by LumiDust** [anlen123/nonebot_plugin_pixiv#12]
大佬想请教下p站的cookie需要哪些呢，也没找到教程，小白比较懵，发现自己配置的cookie不能使用

**Comment by anlen123** [comment]
那啥，好像这个插件有点问题了。应该是p站的界面重做之类的。暂时好像不能用，坏掉了。

**Comment by LumiDust** [comment]
目前是有些pid能识别有些不可以识别，我以为是我cookie有问题_(:з)∠)_

**Comment by anlen123** [comment]
有点麻，得找新方法获取图片地址了。可恶

**Comment by LumiDust** [comment]
加油啊

**Comment by deas1999K** [comment]
普通的图还能搜，R18的全寄，不知道是不是今天下午P站更新了隐藏R18的判定。
pixivbot倒是还能正常搜R18，不过那个看不了动图和多图

**Comment by anlen123** [comment]
反正是因为更新的问题。最近两天我会修复的。麻了。

**Comment by anlen123** [comment]
已修改，可以完美适配了。

**Comment by LumiDust** [comment]
![image](https://user-images.githubusercontent.com/116658416/208559957-8cba7784-0ffa-4a7f-9c92-5a03d539e5c3.png)
cookie是这样的吗，我把requesthead全部复制了

**Comment by LumiDust** [comment]
![image](https://user-images.githubusercontent.com/116658416/208560254-ab25886f-37b9-4aaa-87c3-c36262b20723.png)
这个还是拉不到图片

**Comment by anlen123** [comment]
抱歉，我再看看哈。

**Comment by anlen123** [comment]
可以使用了，记得更新一下版本。
pip install nonebot_plugin_pixiv --upgrade

**Comment by LumiDust** [comment]
![image](https://user-images.githubusercontent.com/116658416/208578987-f71e205b-d79a-4947-8c40-1e8153a079b6.png)
这种是因为我的cookie设置吗

**Comment by LumiDust** [comment]
我是复制的全部这个
![image](https://user-images.githubusercontent.com/116658416/208579068-2f72463b-3f56-4968-9731-3c813c50cc83.png)

**Comment by anlen123** [comment]
> 

报这个没有关系，报这个就是Pid不存在

**Comment by anlen123** [comment]
你看看版本是不是1.1.2

**Comment by LumiDust** [comment]
是的，是1.1.2

**Comment by anlen123** [comment]
cookies只影响动图的发送。你发给我pid，我试试？

**Comment by LumiDust** [comment]
原来是这样，那我找狗群友决斗一下，我估计是他们的pid有问题

**Comment by LumiDust** [comment]
![image](https://user-images.githubusercontent.com/116658416/208580574-1e32df28-f670-4b3d-b11c-d73a4a3e260a.png)
我没看明白这个报错，大佬你可以试试

**Comment by LumiDust** [comment]
这个图片应该不是r18的，我是把r18功能关闭的

**Comment by LumiDust** [comment]
版本是上的最新的1.1.2的

**Comment by anlen123** [comment]
我服了，这个pid真的有问题，你试试其他的pid

**Comment by anlen123** [comment]
所有问题都修复了，用了官方的API了，不会有问题了，而且还支持了黑名单，具体看README.md

**Comment by anlen123** [comment]
最新版本1.1.3

**Comment by LumiDust** [comment]
好的我试试
