### ISSUE TITLE
部分图片无法查询以及图片丢失问题

### ISSUE THREAD

**Issue by deas1999K** [anlen123/nonebot_plugin_pixiv#14]
![image](https://user-images.githubusercontent.com/56710051/208626694-dd2305c7-d388-4307-9bde-6c7aac5c72a1.png)
1.1.3换API之后，有一部分图片的路径无法被官方api识别，在Chrome中会显示为none（我有点怀疑是我个人地区设置的问题，我先用着1.1.2也行）
![image](https://user-images.githubusercontent.com/56710051/208627248-01af7d83-0586-42b5-b5d6-b8bf4ce600fa.png)
Edge浏览器能正常显示，但我太菜了，用requests从上面爬下来之后还是none（悲）
————
另外图片丢失好像是146~158行的num整歪了，多图提取时会丢失p1
![image](https://user-images.githubusercontent.com/56710051/208628121-634b5299-5c29-4559-9cab-7a5d9a567232.png)
我现在暂时是把146行改成num=0用

**Comment by anlen123** [comment]
好家伙，我这就是正常的呢，看看是不是cookies的问题，更新一下。
还有丢失p1那个，还真是，我看看咋改。

**Comment by anlen123** [comment]
> 好家伙，我这就是正常的呢，看看是不是cookies的问题，更新一下。 还有丢失p1那个，还真是，我看看咋改。

<img width="328" alt="image" src="https://user-images.githubusercontent.com/49887895/208631565-9539635b-7e5c-4903-b36e-2541b42b123f.png">

**Comment by anlen123** [comment]
成了，我修改好了。我用第三方的api兜底官方api查不到的，你试试看。

**Comment by anlen123** [comment]
记得更新一下

**Comment by deas1999K** [comment]
ok，没问题了，大佬牛逼ヽ(≧∀≦)ﾉ

**Comment by devil233-ui** [comment]
> 成了，我修改好了。我用第三方的api兜底官方api查不到的，你试试看。

好像还是不太行。麻烦您试试？
https://www.pixiv.net/artworks/127960893
![Image](https://github.com/user-attachments/assets/59842777-91af-4d6b-b48b-530d429b438e)
https://www.pixiv.net/artworks/122230506
![Image](https://github.com/user-attachments/assets/ec47fcf3-f696-48cb-bb54-2259a5f20264)

**Comment by devil233-ui** [comment]
https://pixiv.cat/ 这个其实可以加进项目里，进行二次兜底？
