### ISSUE TITLE
debian11下动图是单张图片发送

### ISSUE THREAD

**Issue by YipSzeho** [anlen123/nonebot_plugin_pixiv#15]
配置如下
`IMGROOT=/root/nonebot`
`AIOHTTP=http://192.168.50.30:7890`
`FFMPEG=/usr/bin/ffmpeg`
`PIXIV_COOKIES=1??????7_c?????????I`
`PIXIV_R18=True`
是否为cookies配置有误？

**Comment by anlen123** [comment]
有可能是Bug，你更新一下插件再试试呢。
