### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by YouYouLip** [anlen123/nonebot_plugin_pixiv#17]
ERROR: Could not install packages due to an OSError: [WinError 5] 拒绝访问。: 'D:\\NoneBot-LittlePaimo\\.venv\\Lib\\site-packages\\cv2\\cv2.pyd'
Check the permissions.
使用NB安装会报如上错误
如果使用pip安装虚拟环境里并不会有插件 这是怎么一回事...
更离谱的是 在仓库中copy到plugin中运行bot还会直接闪退。。。删掉就没事

**Comment by YouYouLip** [comment]
仓库中copy到plugin运行闪退是因为我没把`pyproject.toml`pixiv依赖注入去掉

pip安装的话会显示
`Defaulting to user installation because normal site-packages is not writeable
Collecting gpt3
  Using cached gpt3-0.0.1-py3-none-any.whl (2.0 kB)
Installing collected packages: gpt3
Successfully installed gpt3-0.0.1`

是因为pip不适配在.venv环境中吗（？

**Comment by anlen123** [comment]
这个，你还是直接pip安装使用吧。应该不是插件问题，你再好好研究一下环境呢，推荐conda吧，如果是linux推荐miniconda来控制python环境。

**Comment by YouYouLip** [comment]
> 这个，你还是直接pip安装使用吧。应该不是插件问题，你再好好研究一下环境呢，推荐conda吧，如果是linux推荐miniconda来控制python环境。

没错 确实不是插件的问题 我不知道为什么我poetry shell进的venv环境 我在venv环境里pip 结果给我安到我默认的Python目录下的site-packages里了（？

**Comment by YouYouLip** [comment]
@anlen123 想请教一下代理配置问题http://ip:port这个应该怎么配置 我不管怎么配置都是远程计算机拒绝访问或者是超时，aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host www.pixiv.net:443 ssl:default [信号灯超时时间已到]，取消代理配置用全局梯子申请访问却还是超时 还有ffmpeg这个 如果我的ffmpeg在c盘根目录下的话格式就是FFMPEG=/ffmpeg-master-latest-win64-gpl/bin/ffmpeg对吗（？

**Comment by anlen123** [comment]
1.ffmpeg这个，你用的是windows的话，就直接复制文件栏上的地址。
2.代理这个，得看你用的是哪个工具，clash的话，



你可以开全局在cmd里面用
set http_proxy=http://127.0.0.1:端口号
set https_proxy=http://127.0.0.1:端口号
把你的cmd设置为代理环境，用curl cip.cc看是不是你的机场地址。
&nbsp;


1761512493
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月14日(星期二) 下午5:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [anlen123/nonebot_plugin_pixiv] 安装报错 (Issue #17)





 
@anlen123 想请教一下代理配置问题http://ip:port这个应该怎么配置 我不管怎么配置都是远程计算机拒绝访问或者是超时，aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host www.pixiv.net:443 ssl:default [信号灯超时时间已到]，取消代理配置用全局梯子申请访问却还是超时 还有ffmpeg这个 如果我的ffmpeg在c盘根目录下的话格式就是FFMPEG=/ffmpeg-master-latest-win64-gpl/bin/ffmpeg对吗（？

**Comment by YouYouLip** [comment]
> 1.ffmpeg这个，你用的是windows的话，就直接复制文件栏上的地址。 2.代理这个，得看你用的是哪个工具，clash的话， 你可以开全局在cmd里面用 set http_proxy=[http://127.0.0.1:端口号](http://127.0.0.1:%E7%AB%AF%E5%8F%A3%E5%8F%B7) set https_proxy=[http://127.0.0.1:端口号](http://127.0.0.1:%E7%AB%AF%E5%8F%A3%E5%8F%B7) 把你的cmd设置为代理环境，用curl cip.cc看是不是你的机场地址。 &nbsp; 1761512493 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年2月14日(星期二) 下午5:08 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [anlen123/nonebot_plugin_pixiv] 安装报错 (Issue #17) @anlen123 想请教一下代理配置问题http://ip:port这个应该怎么配置 我不管怎么配置都是远程计算机拒绝访问或者是超时，aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host [www.pixiv.net:443](http://www.pixiv.net:443) ssl:default [信号灯超时时间已到]，取消代理配置用全局梯子申请访问却还是超时 还有ffmpeg这个 如果我的ffmpeg在c盘根目录下的话格式就是FFMPEG=/ffmpeg-master-latest-win64-gpl/bin/ffmpeg对吗（？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

感谢回复 稍后就去试试看
