### ISSUE TITLE
发送动图报错

### ISSUE THREAD

**Issue by PROBEFISH** [anlen123/nonebot_plugin_pixiv#19]
我想问下我已经把ffmpeg的地址填好了，也按之前有人说的解决方法按照了unzip，也把unzip加入到了环境变量里，可是还是不能发送动图，以有动图就会报错。是我哪步做错了吗还是哪里填错了
![CB4LXXA)IU45MG(%R8G(E7Q](https://user-images.githubusercontent.com/108982252/226407070-e9656e53-08ec-4a81-9554-a114831dcfb2.png)
![XIFOVHK }0R3TM{M~FBHL4J](https://user-images.githubusercontent.com/108982252/226407085-67c83be7-ecfb-488d-87b8-1617dcc7db94.png)
![8R20GJ28@TR41_@){D7D$FS](https://user-images.githubusercontent.com/108982252/226407092-29709131-3073-469c-9ab1-ba56e0e7c06c.png)

**Comment by anlen123** [comment]
看报错, 貌似不是压缩问题

**Comment by PROBEFISH** [comment]
我按https://github.com/anlen123/nonebot_plugin_pixiv/issues/6里面说的把return (stdout + stderr).decode()改成了return (stdout + stderr).decode('gb2312')，然后把init里面的解压给给改成了tar就好了
