### ISSUE TITLE
关于保存图片路径的问题

### ISSUE THREAD

**Issue by kumiko-desu** [anlen123/nonebot_plugin_pixiv#2]
哈哈又是我，我在使用的过程中发现一个小小的bug，根本原因是发送消息时，是通过CQ码内写入图片路径发送的，所以只要 `go-cqhttp` 和 `nonebot` 不是部署在一起就无法正常运行（除非做一下路径映射）。
因为我的 `nonebot` 是通过 `docker` 来部署的，`go-cqhttp` 则是部署在宿主机中的，`go-cqhttp` 上传时无法访问到容器中的文件（`docker` 中的路径是 `/app/pixivQQbotFiles`， 宿主机的路径是 `/root/nonebot2/pixivQQbotFiles` ）。
并且我测试了一下，因为是通过CQ码内写入图片路径发送的，导致 `IMGROOT` 不能使用相对路径。

**Comment by anlen123** [comment]
这个问题好像没办法解决呢，docker里面部署nonebot，代码肯定是运行在docker里面的，gocq在宿主机上，两个地方环境不一定了，请问你有什么解决办法呢，只能做docker和宿主机的映射了吧。

**Comment by anlen123** [comment]
意思是可以弄成，不是写入图片路径发送，其实pixiv做了防盗链，直接输入url的源地址，发不了图片呢。

**Comment by kumiko-desu** [comment]
我目前是做了docker和宿主机的路径映射，能够正常使用了。
可能可以参考一下这个插件的写法，通过图片的base64码发送。

https://github.com/ayanamiblhx/nonebot_plugin_setu/blob/af196b4ea94e93cfaf49677b18a65eb6e121fb49/nonebot_plugin_setu/__init__.py#L71-L72

https://github.com/ayanamiblhx/nonebot_plugin_setu/blob/af196b4ea94e93cfaf49677b18a65eb6e121fb49/nonebot_plugin_setu/getPic.py#L65-L68

**Comment by anlen123** [comment]
你试试呢，改好了。要是成功了，我就把这个关了。

**Comment by kumiko-desu** [comment]
测试完了，能正常运行，并且也能用相对路径了。🥰
