### ISSUE TITLE
压缩动态图片时报错: list index out of range

### ISSUE THREAD

**Issue by salspica** [anlen123/nonebot_plugin_pixiv#23]
使用动图pid 95004423

**日志**
  File "C:\Users\Administrator\NBbBOT\.venv\Lib\site-packages\nonebot_plugin_pixiv\__init__.py", line 301, in GIF_send
    chang = int(msg.split(" ")[-3]) // 2
IndexError: list index out of range

不会编程只能绕过压缩步骤但动图太大qq也没法成功发送
还有疑问，更极端一点的比如pid 106439513，下载到本地进行合成后gif大小有103mb，这种也能顺利压缩成qq能发送的大小吗？

**Comment by anlen123** [comment]
不能, 这是是QQ接口限制了, 代码应该没问题, 啥动图这么大.

**Comment by salspica** [comment]
哈哈它就是那么大，感谢解答
