### ISSUE TITLE
qq中无法显示图片

### ISSUE THREAD

**Issue by yu-xinx** [anlen123/nonebot_plugin_pixiv#24]
qq中无法显示图片
![QQ截图20230905185315.png](https://s2.loli.net/2023/09/05/OeP5w3MATjLFdCG.png)
不知道是不是因为18的原因

**Comment by anlen123** [comment]
你pixiv帐号的cookies配置了吗, 应该不是插件问题, QQ问题吧

**Comment by yu-xinx** [comment]
cookies配置了目前就这个id不能显示
不知道为什么没有显示请求
![QQ截图20230905215946.png](https://s2.loli.net/2023/09/05/4rMnmkXQvGYDyfC.png)
