### ISSUE TITLE
R18无法关闭

### ISSUE THREAD

**Issue by 1367393986** [anlen123/nonebot_plugin_pixiv#25]
![P T)4@1UK4C DRB67$IBJDN](https://github.com/anlen123/nonebot_plugin_pixiv/assets/61593338/ec6f5712-6c6b-4d37-9f6c-d8d5372e213f)

**Comment by 1367393986** [comment]
说明文档中PIXIV_R18=["123", "456"]书写错误，要改成PIXIV_R18=[’123‘, ’456‘]，不然eval()转不成数组😓

**Comment by anlen123** [comment]
已修改
