### ISSUE TITLE
无法搜图

### ISSUE THREAD

**Issue by iven13465** [anlen123/nonebot_plugin_pixiv#4]
![Q KIXHGHBB_LAUQHZB1 NKC](https://user-images.githubusercontent.com/95957360/185531518-503ace7e-6611-401d-b3d4-63abb85a3990.png)

.env
![EKF23HI UWW@48L~V0(WF@M](https://user-images.githubusercontent.com/95957360/185531527-6a6cccbb-edd7-442e-a065-76ad4fdd15ef.png)
代理是正常的

**Comment by anlen123** [comment]
我是正常的呢，不管是国外的机器不用代理还是国内机器用代理，都没有发生这样的情况。

**Comment by anlen123** [comment]
你检查一下代理是否没配置好呢。

**Comment by iven13465** [comment]
> 你检查一下代理是否没配置好呢。

没事了，是我cookies失效了
