### ISSUE TITLE
win下发送GIF报错

### ISSUE THREAD

**Issue by CCYellowStar** [anlen123/nonebot_plugin_pixiv#6]
![image](https://user-images.githubusercontent.com/47291058/189062451-075485a5-5e12-4f95-b0be-1f3b9b4b7eea.png)

**Comment by anlen123** [comment]
Win，你的ffmpeg配置正确了吗，文件夹的位置还有。我等哈在win上看看是否有这个问题，平时我都用的linux和mac没问题来着。

**Comment by CCYellowStar** [comment]
是配置到bin那个文件夹吗，不过我看报错是在解压的命令里

**Comment by anlen123** [comment]
你看见__init__.py的277行，这个unzip解压，你看看得安装个。或者你看哪一步错了调一调。
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/49887895/189295378-47e655b9-2f6d-4941-a25e-b713e0db4b23.png">

**Comment by CCYellowStar** [comment]
你在win正常吗

**Comment by anlen123** [comment]
现在没空去测试，明天我有空去试试，看看是哪儿的问题。

**Comment by anlen123** [comment]
抱歉，我win上aiohttp都报错，莫名奇妙，貌似是不支持win的，你可以自己看着改代码吗。

**Comment by Lc113** [comment]
同样的问题，我把报错行
return (stdout + stderr).decode() 
改成了
return (stdout + stderr).decode('gbk')
就不会有解码报错了

但是出现了找不到gif的报错

**Comment by anlen123** [comment]
有可能是，win和linux的路径的问题，看看反斜杠那些。

**Comment by Lc113** [comment]
破案了，windows确实是需要安装unzip，不然不能执行解压

不过后面图片转gif也没有正常执行
设置系统变量后修改程序内ffmpeg路径ffmpeg= "ffmpeg"就解决了

结论：主要就是命令行不太一样(
