### ISSUE TITLE
报错Pixiv_cookies未配置

### ISSUE THREAD

**Issue by ddlixin** [anlen123/nonebot_plugin_pixiv#8]
小白第一次配置，东西不是放这个下面么，不能执行
![1662954791437](https://user-images.githubusercontent.com/49864556/189570996-04833159-a1b4-4978-8bb4-e76f2236214d.png)

**Comment by anlen123** [comment]
配置在.end.dev里面哦。你看看用的什么环境。pro就在.end.pro里面。不是在这配置。

**Comment by ddlixin** [comment]
> 

谢谢，找到原因了

**Comment by anlen123** [comment]
不用谢，谢谢使用本插件，哈哈哈(*^__^*)

**Comment by anlen123** [comment]
不用谢，谢谢使用本插件，哈哈哈(*^__^*)
