### ISSUE TITLE
成功加载无反应

### ISSUE THREAD

**Issue by LumiDust** [anlen123/nonebot_plugin_pixiv#9]
![Q@WIXBKDZ2N({6Q(1(59S0P](https://user-images.githubusercontent.com/116658416/199908728-592445f1-9dac-4493-975b-295bf36f7fc4.png)
![1UVQ`GBQX$)WMEL I$81E%F](https://user-images.githubusercontent.com/116658416/199908792-e2c46494-a357-45c3-87ec-10d4137924c4.png)
设置和加载都没问题应该，指令使用没反应

**Comment by anlen123** [comment]
看看后台，错误。或者有可能，前面要加/

**Comment by anlen123** [comment]
解决了吗？

**Comment by LumiDust** [comment]
好像没有解决

**Comment by anlen123** [comment]
你的登录机器人的网络是可以科学上网的吗？还是用的梯子？
如果是本身就是国外的网络不需要配置。
如果是梯子的话，需要配置一个AIOHTTP
又或者，你自己看看日志嘛。报错信息是啥

**Comment by LumiDust** [comment]
![image](https://user-images.githubusercontent.com/116658416/208402273-32cd2905-9394-4600-af0d-f7c0b79e89c3.png)
是这么配置的，设置的是全局代理

**Comment by LumiDust** [comment]
！！刚才没反应，重启了两遍好像可以了

**Comment by anlen123** [comment]
好的好的，感谢使用，如果还不行，有可能是你的v2ray没有设置http代理，可能是sock5

**Comment by LumiDust** [comment]
好的，谢谢大佬
